databases:
  - name: influencons
    databaseName: influencons
    user: influencons

services:
  - type: web
    name: influencons
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: influencons
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false